# Site settings
title: Amy Cards
email: no-reply@amycards.me
url: https://amycards.me
description: "The collectible hockey cards everyone's been waiting for!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#ffffff'

# Footer settings
footer: Amy Cards

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Build settings
markdown: kramdown
permalink: pretty